fix: totalEstimate and totalHours return hours
joshuawootonn/time-track pull request #117
Opened 2023-08-17 02:16 UTC by odin5on

2023-08-17 02:34 UTC, joshuawootonn commented on api/common/models/project.js
> +                  return total + (currentActivity.length / 60)
<img width="322" alt="CleanShot 2023-08-16 at 21 31 01@2x" src="https://github.com/joshuawootonn/time-track/assets/20950876/39316d8d-eac4-4090-b55f-b232e47da79e">


On second thought, I think all these lengths should be in minutes. Then we can format them any way we like on the frontend.

2023-08-17 02:35 UTC, joshuawootonn commented on api/common/models/project.js
> +                  return total + (currentActivity.length / 60)
When you do these types of divisions make sure you `Math.floor`. We don't want to have to handle any wild decimal places on the FE.

2023-08-17 02:36 UTC, joshuawootonn requested changes
When you do these types of divisions make sure you Math.floor. We don't want to have to handle any wild decimal places on the FE.

2023-08-17 02:47 UTC, joshuawootonn commented
In addition to these changes, you will need to update the FE to correctly display the spans of time. I would use `var % 60` for getting minutes & `(var / 60) * 60` for getting the hours

2023-08-18 15:20 UTC, odin5on commented
went ahead and added the hourse type fix to this PR

2023-08-19 17:43 UTC, joshuawootonn requested changes
Just need to update the formatting. Almost there!

2023-08-19 17:43 UTC, joshuawootonn commented on desktop/src/containers/ForemanProject/projectSummary.container.tsx
> +          {Math.round(projectSummary.minutesWorkedThisWeek / 60)}
I think this will give us "Hours Worked This Week: 12" when I also want to include the minutes like: 
"Hours Worked This Week: 12:45"

2023-08-19 17:43 UTC, joshuawootonn commented on desktop/src/containers/ForemanProject/projectSummary.container.tsx
> +          {Math.round(projectSummary.minutesWorkedThisWeek / 60)}
<img width="659" alt="CleanShot 2023-08-19 at 12 42 16@2x" src="https://github.com/joshuawootonn/time-track/assets/20950876/f52d3567-40b0-4d2d-a5d8-476cd54d164a">
For this example we want

2023-08-19 17:43 UTC, joshuawootonn commented on desktop/src/containers/ForemanProject/projectSummary.container.tsx
> +          {Math.round(projectSummary.minutesWorkedThisWeek / 60)}
6:15 | 423:45 | 187:45

2023-09-01 01:18 UTC, joshuawootonn commented on desktop/src/containers/ForemanProject/projectSummary.container.tsx
> +          {Math.floor(projectSummary.minutesWorkedYesterday / 60)}:{String(projectSummary.minutesWorkedYesterday%60).padStart(2,'0')}
What are we getting for using `padStart` here?

2023-09-01 01:20 UTC, joshuawootonn approved these changes

2023-09-01 16:19 UTC, merged